- go.sh
Typo. It said implemeted, not implemented.
> Update go.sh - a typo

- go.sh
Cherry-picked this script onto 1.6 branch as requested
> implement go.sh in stable-v1.6

- go.sh
Tgl is supported now.
This commit is cherry-picked from the master branch
> Add tgl into go.sh

- go.sh
- publish.sh
- Add JSL and EHL support
- Add sof/community fw support in go.sh
- Fix ldc file mode in publish.sh
> Update go.sh and publish.sh with 1.6 release

- README.md
Add installation guide for latest v1.6.1 release.
Signed-off-by: Pan Xiuli <xiuli.pan@linux.intel.com>
> README: update the installation guide

- go.sh
- publish.sh
Fix go.sh issue with given test ROOT
Fix publish.sh issue when run with existing branch to do some modify or add some files
> some fix for scripts

- README.md
> README.md: remove some v1.7 hardcoding

- HOWTO-new-release.md
For the formatted view go to https://github.com/thesofproject/sof-bin/pull/55/files -> `...` (top right) -> View File
> New file HOWTO-new-release.md

- HOWTO-new-release.md
> HOWTO-new-release.md: move "immutable" warning at the top

- tarball_one_version.sh
- tarball_topologies_only.sh
> Add new tarball_topologies_only.sh

- HOWTO-new-release.md
Should avoid #87 from happening again, see commits just before this one.
> HOWTO-new-release: add symbolic links to checklist

- .github/workflows/BATS.yml
- tarball_one_version.sh
- tarball_topologies_only.sh
- tests/common_helpers.bash
- tests/tests.bats
See commit messages (and test results!)
> Add automated tests for tarball*.sh scripts

- tests/tests.bats
This makes it easy to add new tests.
> tests.bats: make version numbers variables / test parameters

- tests/tests.bats
> tests: refactoring to allow test hacks after download

- tarball_multi_releases.bash
- tests/tests.bats
> tarball_multi_releases: fix consistency with tarball_one_version, add new tests

- compare_signed_unsigned.py
> compare_signed_unsigned.py: add ability to compare two files

- HOWTO-new-release.md
Add new sof/versions.json to the check list
> HOWTO-new-release.md: add new sof/versions.json

- install.sh
Easy to extend to xBSD or other if needed.
> install.sh: add Darwin test workaround

- tests/tests.bats
> add install.sh test for new, IPC4 v2.7

- .gitignore
- Makefile
- tarball_multi_releases.bash
- tests/README.md
> Add "make clean", .gitignore and small tests/README.md
