thesofproject/sof-bin

- LICENCE.NXP
- Notice.NXP
LICENCE.NXP contains the license for firmware binaries
and points to Notice.NXP which contains the license
for firmware sources.
Signed-off-by: Bogdan Florin Vlad <bogdan.vlad@nxp.com>
Signed-off-by: Daniel Baluta <daniel.baluta@nxp.com>
Cc: @bogvlad1
> NXP: Add NXP license and notice files

- publish.sh
Add a new publish script to do following task:
- branch creation
- dictionary generation
- binary copy
- binary rename
usage: ./publish.sh -v RELEASE_VERSION -i INTEL_SIGNED_SRC_DIR
-p PUBLIC_SIGNED_SRC_DIR -t TOOLS_SRC_DIR -l TPLG_SRC_DIR
Signed-off-by: Pan Xiuli <xiuli.pan@linux.intel.com>
> helper: add publish scripts for new release

- go.sh
* Fixed the TODO comment which was inaccurate as packaging became publish.sh responsibility
* Went with a fallback approach on SOF_VERSION - try to use git and if not ask the user to specify it - since this repo is targetted at packagers, they should already know as they had to check out the correct branch
I had a look through the pull requests on this topic existing and want to pre-emptively address the following:
> Can you use longer variable names to minimize collision risks? Examples: FS_ROOT, INTEL_FW_PATH, SOF_VERSION,...
> Or even safer and simpler: make these local in the new, main() function.
> Could you move all the code into a main() function? It makes it easier to source the script for interactive testing by commenting out just the final line, lets add functions in any order …
> implement go.sh

- go.sh
Tgl is supported now.
Signed-off-by: Bard Liao <yung-chuan.liao@linux.intel.com>
> Add tgl into go.sh

- go.sh
- publish.sh
check FW binary key with [sof_ri_info.py](https://github.com/thesofproject/sof/blob/master/tools/sof_ri_info/sof_ri_info.py) tool
TODO:
Example to use:
```
./publish.sh -c -i ~/work/sof/release/1.6.1/production/
========================================================================
checking /home/pxl/work/sof/release/1.6.1/production/sof-apl.ri
1f f4 58 74 64 d4 ae 90 ... b5 c2 49 4e 2a 5f 47 c2 (APL Intel prod key)
sof-apl.ri get correct key
========================================================================
checking /home/pxl/work/sof/release/1.6.1/production/sof-cnl.ri
41 a0 3e 14 1e 7e 29 72 ... cd 1d fa fd e8 a0 ba 91 (CNL Intel prod key)
sof-cnl.ri get correct key
========================================================================
checking …
```
> update publish script to check FW binary

- v1.9.x/sof-v1.9/community/sof-adl-s.ri
- v1.9.x/sof-v1.9/community/sof-adl.ri
- v1.9.x/sof-v1.9/sof-adl-s.ri
Manually created for now, will be automatically generated once
sof commit 5a7a135f018 is backported (https://github.com/thesofproject/sof/pull/4804)
> sof-v1.9: add ADL symbolic links

- .github/workflows/codestyle.yml
- tarball_one_version.sh
- tests/tests.bats
Note there is NO commitment to support macOS, it is just a convenience available right now - until we really need something Linux-specific.
> Add shellcheck Github Action, minor mac fixes

- tests/tests.bats
"Only in sof-bin-v2.3/sof-v2.3: sof-tgl.ri" was not very useful, changed to:
"Only in /home/user.testruns/run-62m5fY/sof-bin-v2.3/sof-v2.3: sof-tgl.ri"
> tests: show name of temporary "testruns" directory when diff fails

- tarball_multi_releases.bash
It should be fatal to release broken symlinks but resolving symlinks thanks to a combination of releases should be OK. So just WARN.
> tarball_multi_releases.sh: downgrade symlink pre-check to WARNING

- install.sh
- tests/tests.bats
Should avoid #80-like confusion.
> install.sh: check the argument

- tests/common_helpers.bash
- tests/compare_signed.bats
3 commits. Main one: compare_signed.bats: define BATS_RUN_COMMAND when not available.
This makes failure logs MUCH more readable!
> compare_signed.bats: define BATS_RUN_COMMAND when not available

- tests/compare_signed.bats
- v2.4.x/sof-v2.4.1/intel-signed/sofz-rpl-s.ri
- v2.4.x/sof-v2.4.1/intel-signed/sofz-rpl.ri
- v2.4.x/sof-v2.4.1/sofz-adl-s.ri
- v2.4.x/sof-v2.4.1/sofz-adl.ri
- v2.4.x/sof-v2.4.1/sofz-rpl-s.ri
- v2.4.x/sof-v2.4.1/sofz-rpl.ri
Only TGL is intel-signed in v2.4.1
> Remove broken intel-signed ADL and RPL symlinks from v2.4.1 

- tests/compare_signed.bats
List all reproducibility issues now that we know much better.
> tests/compare_signed.bats: list all v2.4 and v2.5 reproducibility bugs

- tarball_multi_releases.bash
Real bad luck:
- The v2.3 git tag was never created
- Nothing ever gets deleted in this repo except one of the directories in the example.
Use a different tag and different subdirectory.
> tarball_multi_releases.bash: fix example in -h string

- README.md
- install.sh
Add support for installing SOF firmare binary and related topology files according to the /lib/firmware layout expected by Linux SOF driver:
FW:
- /lib/firmware/intel/sof-ipc4/mtl/sof-mtl.ri
Topology files:
- /lib/firmware/intel/sof-ace-tplg/*.tplg
Reference:
- https://github.com/torvalds/linux/blob/v6.5/sound/soc/sof/intel/pci-mtl.c#L23
> install.sh: add support for Intel Meteor Lake binaries

- tarball_multi_releases.bash
Add support for setting the tarball version explicitly. This is done with "-r vCUSTOM" option.
> tarball_multi_releases.bash: add -r option to set tarball version

- tests/compare_signed.bats
Add a brand new test because the existing v2.* one is already too long
with too many exceptions.
Yes copy/paste is OK-ish in test code :-)
This test does nothing for now but I tested it with mock .ri files.
> tests/compare_signed: add v2.*/sof-ipc4-v*

- tests/tests.bats
Also add some logging in generic install test code.
> Add test for new, IPC4 tarball_multi_release.sh 2023.9

- v2.10.x/sof-ipc4-v2.10/tgl/community/sof-rpl.ri
Remove unneeded tgl/community/sof-rpl.ri file from the v2.10 release.
> v2.10.x: remove extra sof-rpl.ri

- v2.11.x/sof-ipc4-v2.11.1/arl/intel-signed/sof-arl.ri
- v2.11.x/sof-ipc4-v2.11.1/arl/sof-arl.ri
Intel Arrow Lake shares the same audio DSP and can use the same firmware binaries as MTL, but as kernel driver looks up the firmware with a unique name, add the missing symbolic links for signed binaries.
> [DNM] Add missing links for SOF v2.11.1 signed Intel binaries for ARL

- README.md
- tests/tests.bats
Clarify the README.md text to emphasize that this repository and upstream release process is open to all vendors. Some of the examples are Intel specific and/or use e.g. Intel specific firmware paths as examples, as that is what is currently distributed.
> README.md: clarify platform applicability
